// session
export const CHECK_VALIDATE_ACCESS = 'CHECK_VALIDATE_ACCESS';

// Get customer transaction
export const GET_CUSTOMER_TRANSACTION = 'GET_CUSTOMER_TRANSACTION';
export const GET_CUSTOMER_TRANSACTION_SUCCESS = 'GET_CUSTOMER_TRANSACTION_SUCCESS';
export const GET_CUSTOMER_TRANSACTION_FAILED = 'GET_CUSTOMER_TRANSACTION_FAILED';

// Get list gateway
export const REQUEST_LIST_GATEWAY = 'REQUEST_LIST_GATEWAY';
export const REQUEST_LIST_GATEWAY_SUCCESS = 'REQUEST_LIST_GATEWAYL_SUCCESS';
export const REQUEST_LIST_GATEWAY_FAILED = 'REQUEST_LIST_GATEWAY_FAILED';

// create transaction 
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAILED = 'CREATE_TRANSACTION_FAILED';

// Get detail transaction
export const GET_DETAIL_TRANSACTION = 'GET_DETAIL_TRANSACTION';
export const GET_DETAIL_TRANSACTION_SUCCESS = 'GET_DETAIL_TRANSACTION_SUCCESS';
export const GET_DETAIL_TRANSACTION_FAILED = 'GET_DETAIL_TRANSACTION_FAILED';

// get  transaction error
export const GET_TRANSACTION_ERRROR = 'GET_TRANSACTION_ERRROR';
export const GET_TRANSACTION_ERRROR_SUCCESS = 'GET_TRANSACTION_ERRROR_SUCCESS';
export const GET_TRANSACTION_ERRROR_FAILED = 'GET_TRANSACTION_ERRROR_FAILED';
